# Trabajo Fin de Máster  
### Análisis de la Ciudad mediante Aprendizaje Supervisado  
#### Detección Automática de Tipologías Residenciales y Patrones de Cerramiento: Interpretabilidad vs Rendimiento

**Master Universitario en Ciencia de Datos e Ingeniería de Computadores (Universidad de Granada)**

> **Autor:** David Fernández Martínez    
> **Email personal:** david.fernxndez.martinez@gmail.com  
> **Email académico:** davidfm8@correo.ugr.es  
> **LinkedIn:** [linkedin.com/in/david-fernández-martínez](https://www.linkedin.com/in/david-fern%C3%A1ndez-mart%C3%ADnez/)  
> **GitHub:** [github.com/davidfernxndez](https://github.com/davidfernxndez)

---

## Evaluación de rendimiento

### 📝 Descripción del notebook
COMPLETAR...

### Indice de contenidos
COMPLETAR...

# Configuración de entorno e *imports*

Este proyecto ha sido realizado en un entorno Anaconda con la versión 3.11.15 de *Python*. Las versiones de las librerias requeridas se encuentran en el fichero *requirements.txt*.

En esta sección se importan las librerias necesarias para la ejecución de este fichero jupyter notebook, se activa el *reload* de módulos externos y se configuran aspectos globales y de reproducibilidad.

In [1]:
# jupyter extensions to automatically reload external modules
%load_ext autoreload
%autoreload 2

In [2]:
import warnings
import random
import numpy as np
import pandas as pd

# Configuration object
from src.config import cfg

In [3]:
# Global configuration
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
warnings.filterwarnings("ignore")

In [4]:
# Reproducibility
SEED = cfg.SEED 
np.random.seed(SEED)
random.seed(SEED)

# 1. Test

In [5]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.ensemble import RandomForestClassifier
from src.performance import performance_experiment

In [6]:
pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", RandomForestClassifier(
        random_state=42
    ))
])


param_grid = {
    "model__n_estimators": [50, 100],
    "model__max_depth": [5, 10, None]
}  

 
macro_results_df, class_results_df = performance_experiment(
    config=cfg,
    pipeline=pipeline,
    param_grid=param_grid,
    experiment_name="Test_2"
)

============================================================
RUNNING EXPERIMENT: Test_2
============================================================

OUTER FOLD 0
- Outer Train and Test Set correctly selected.
- Inner sets for Inner Cross Validation correctly selected.
- Grid Search initiated
Fitting 3 folds for each of 6 candidates, totalling 18 fits

OUTER FOLD 1
- Outer Train and Test Set correctly selected.
- Inner sets for Inner Cross Validation correctly selected.
- Grid Search initiated
Fitting 3 folds for each of 6 candidates, totalling 18 fits

OUTER FOLD 2
- Outer Train and Test Set correctly selected.
- Inner sets for Inner Cross Validation correctly selected.
- Grid Search initiated
Fitting 3 folds for each of 6 candidates, totalling 18 fits

OUTER FOLD 3
- Outer Train and Test Set correctly selected.
- Inner sets for Inner Cross Validation correctly selected.
- Grid Search initiated
Fitting 3 folds for each of 6 candidates, totalling 18 fits

OUTER FOLD 4
- Outer Train and Test Set correctly selected.
- Inner sets for Inner Cross Validation correctly selected.
- Grid Search initiated
Fitting 3 folds for each of 6 candidates, totalling 18 fits

In [7]:
macro_results_df

,outer_fold,accuracy,f1_macro,precision_macro,recall_macro,best_params
0,0,0.937984,0.909151,0.948052,0.882143,"{'model__max_depth': None, 'model__n_estimator..."
1,1,0.953488,0.933873,0.949254,0.923626,"{'model__max_depth': None, 'model__n_estimator..."
2,2,0.953125,0.911631,0.948319,0.888462,"{'model__max_depth': None, 'model__n_estimator..."
3,3,0.929688,0.857655,0.900463,0.833883,"{'model__max_depth': 10, 'model__n_estimators'..."
4,4,0.929688,0.860807,0.891169,0.840476,"{'model__max_depth': 10, 'model__n_estimators'..."

In [8]:
class_results_df

    outer_fold  class  precision    recall        f1  support
0            0      1   1.000000  0.769231  0.869565     13.0
1            0      2   0.910714  0.980769  0.944444     52.0
2            0      3   0.875000  0.875000  0.875000      8.0
3            0      4   0.954545  1.000000  0.976744     42.0
4            0      5   1.000000  0.785714  0.880000     14.0
5            1      1   0.923077  0.923077  0.923077     13.0
6            1      2   0.980769  0.980769  0.980769     52.0
7            1      3   1.000000  1.000000  1.000000      8.0
8            1      4   0.933333  1.000000  0.965517     42.0
9            1      5   0.909091  0.714286  0.800000     14.0
10           2      1   0.923077  1.000000  0.960000     12.0
11           2      2   0.962963  1.000000  0.981132     52.0
12           2      3   1.000000  0.750000  0.857143      8.0
13           2      4   0.955556  1.000000  0.977273     43.0
14           2      5   0.900000  0.692308  0.782609     13.0
15           3      1   0.916667  0.916667  0.916667     12.0
16           3      2   0.981481  1.000000  0.990654     53.0
17           3      3   0.833333  0.714286  0.769231      7.0
18           3      4   0.895833  1.000000  0.945055     43.0
19           3      5   0.875000  0.538462  0.666667     13.0
20           4      1   0.916667  0.916667  0.916667     12.0
21           4      2   0.928571  1.000000  0.962963     52.0
22           4      3   0.833333  0.714286  0.769231      7.0
23           4      4   0.977273  1.000000  0.988506     43.0
24           4      5   0.800000  0.571429  0.666667     14.0